Feature/ep 9 load users
jortiz3109/escuela-php-panel pull request #14
Opened 2021-10-25 22:26 UTC by RobertJDevOP

Se realiza la lista de usuarios retornándolo al template

2021-11-16 19:16 UTC, jortiz3109 requested changes
Falta revisar pruebas

2021-11-16 19:16 UTC, jortiz3109 commented on composer.json
> +        "php": "8.0",
Ojo con este cambio.. puede derivar en errores luego

2021-11-16 19:16 UTC, jortiz3109 commented on app/Filters/Conditions/Created_at.php
> +class Created_at extends Condition
El nombre de esta clase no cumple PSR

2021-11-16 19:16 UTC, jortiz3109 commented on app/Filters/Conditions/EnabledAt.php
> +class EnabledAt extends Condition
¿Cúal es la función de esta condición?

2021-11-16 19:16 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        return view('users.index', $viewModel->toArray());
Dar un salto de línea para cumplir PSR

2021-11-16 19:16 UTC, jortiz3109 commented on app/Models/User.php
> +    protected $appends = ['date_formatted',
No cumple PSR

2021-11-16 23:23 UTC, jortiz3109 commented on app/Models/User.php
> +        return (is_null($this->attributes['enabled_at'])) ? 'Disabled' : 'Enabled';
Utilizar traducciones

2021-11-17 16:17 UTC, RobertJDevOP commented on composer.json
> +        "php": "8.0",
https://github.com/jortiz3109/escuela-php-panel/commit/a661b2c5bdcd79a029000ff012f6bcb1cbfc2be7

2021-11-17 16:18 UTC, RobertJDevOP commented on app/Filters/Conditions/Created_at.php
> +class Created_at extends Condition
https://github.com/jortiz3109/escuela-php-panel/commit/a661b2c5bdcd79a029000ff012f6bcb1cbfc2be7

2021-11-17 16:18 UTC, RobertJDevOP commented on app/Filters/Conditions/EnabledAt.php
> +class EnabledAt extends Condition
https://github.com/jortiz3109/escuela-php-panel/commit/a661b2c5bdcd79a029000ff012f6bcb1cbfc2be7

2021-11-17 16:18 UTC, RobertJDevOP commented on app/Http/Controllers/UserController.php
> +        return view('users.index', $viewModel->toArray());
https://github.com/jortiz3109/escuela-php-panel/commit/a661b2c5bdcd79a029000ff012f6bcb1cbfc2be7

2021-11-17 16:18 UTC, RobertJDevOP commented on app/Models/User.php
> +    protected $appends = ['date_formatted',
https://github.com/jortiz3109/escuela-php-panel/commit/a661b2c5bdcd79a029000ff012f6bcb1cbfc2be7

2021-11-17 16:18 UTC, RobertJDevOP commented on app/Models/User.php
> +        return (is_null($this->attributes['enabled_at'])) ? 'Disabled' : 'Enabled';
https://github.com/jortiz3109/escuela-php-panel/commit/a661b2c5bdcd79a029000ff012f6bcb1cbfc2be7

2021-11-17 16:21 UTC, RobertJDevOP reviewed
Se hace revisión de lo indicado

2021-12-28 00:49 UTC, asilvabe requested changes

2021-12-28 00:49 UTC, asilvabe commented on app/Filters/Conditions/Status.php
> +    }
Refactorizar: en vez de usar las cadenas 'enabled' o 'disabled' sino como booleanos

2021-12-28 00:49 UTC, asilvabe commented on app/Filters/Filter.php
> -
Actualizar con la rama develop
Se debe revisar el método `conditions` para evitar que se dejen por fuera los falores false, y únicamente sacar los null

2021-12-28 00:49 UTC, asilvabe commented on app/Http/Controllers/UserController.php
> +        return view('users.index', $viewModel->toArray());
Primero actuaizar con develop.
Si aún se está usando el toArray, eliminarlo.

2021-12-28 00:49 UTC, asilvabe commented on app/Http/Requests/Users/IndexRequest.php
> +        ];
Revisar qué reglas hacen falta añadir.
Agregar reglas para cada uno de los filtros utilizados.
Recordar usar el `bail`
Revisar también https://github.com/jortiz3109/escuela-php-panel/pull/25#discussion_r774219512

2022-01-13 17:13 UTC, merged