Feature/users registrer
jortiz3109/escuela-php-panel pull request #16
Opened 2021-10-29 21:27 UTC by jeantech-zz

Created register user

2021-10-29 21:30 UTC, jortiz3109 commented
OJO con las convenciones: https://www.conventionalcommits.org/en/v1.0.0/

2021-10-29 21:49 UTC, jortiz3109 requested changes
Hay que tener mucho cuidado con los tipos de dato de retorno.
Hay que mirar con detenimiento que comentarios dejamos en el código

2021-10-29 21:49 UTC, jortiz3109 commented on app/Actions/Register/CreateUser.php
> +    public static function execute(array $userRequest): User
¿Realmente es un "request" lo que estamos recibiendo como parámetro? ¿Porque es un request?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Actions/Register/CreateUser.php
> +        event(new Registered($user));
¿Un evento si debería ser despachado desde una acción?
Es decir: ¿Realmente es reponsabilidad de la acción de crear; despachar el evento en cuestión?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        $userId=auth()->id();
Hace falta el tipo de dato de retorno.
OJO con la indentación y los espacios según PSR...

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        return view('register.create', [
¿Porque no estamos usando un ViewModel?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +    public function store(UserCreateRequest $request)
¿Donde está el tipo de dato de retorno?
¿Porque no estamos usando un viewmodel?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        return view('dashboard', [
Yo no debería retornar una vista en este método del controlador, en su lugar debería redireccionar a una ruta existente con un mensaje.

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Requests/Register/UserCreateRequest.php
> +    /**
¿Estos comentarios si aportan valor?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Requests/Register/UserCreateRequest.php
> +    public function rules()
¿Donde está el tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Requests/Register/UserCreateRequest.php
> +    public function messages()
¿Donde está el tipo de dato de retorno?
¿Que pasó con las traducciones?
¿Si requiero traducir los mensajes de error este si será el mejor enfoque?

2021-10-29 21:49 UTC, jortiz3109 commented on app/Http/Requests/Register/UserCreateRequest.php
> +    public function attributes()
¿Donde está el tipo de dato de retorno?
OJO que este no es el mejor mecanismo para traducir los nombres de los campos

2021-10-29 21:49 UTC, jortiz3109 commented on database/migrations/2021_10_24_224610_add_column_user.php
> +    public function up()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on database/migrations/2021_10_24_224610_add_column_user.php
> +<?php
¿Este nombre de la migración si representa los cambios que se están haciendo en la tabla de la DB?

2021-10-29 21:49 UTC, jortiz3109 commented on database/migrations/2021_10_24_224610_add_column_user.php
> +    public function down()
¿donde está el tipo de dato de retorno?
¿Que pasa con los comentarios que no aportan valor?

2021-10-29 21:49 UTC, jortiz3109 commented on database/migrations/2021_10_24_224610_add_column_user.php
> +            $table->dropForeign(['created_by']);
Estoy eliminando el constraint pero no eliminando el campo

2021-10-29 21:49 UTC, jortiz3109 commented on database/seeders/DatabaseSeeder.php
> +        $this->call(UserSeeder::class);
¿Porque es necesario este seeder?

2021-10-29 21:49 UTC, jortiz3109 commented on database/seeders/UserSeeder.php
> +    public function run()
Tipo de dato de retorno?
Comentarios que no aportan valor

2021-10-29 21:49 UTC, jortiz3109 commented on database/seeders/UserSeeder.php
> +            "password"=>Hash::make('jeante05'),
IMPORTANTE!!! por seguridad ningún código fuente puede tener, usuarios, contraseñas u otros tipos de mecanismos de autentiación en blando.

¿Que ocurre si quiero crear un administrador con otro usuario/contraseña?

2021-10-29 21:49 UTC, jortiz3109 commented on resources/views/layouts/admin.blade.php
> +                            <li><a href="{{ route('register.create') }}"><em class="pr-2 mdi mdi-account-multiple"></em>@lang('Users')</a></li>
Creo que este enlace no va en esta vista

2021-10-29 21:49 UTC, jortiz3109 commented on routes/web.php
> +    Route::name('register.create')->get('/register', [UserController::class, 'create']);
¿Porque una ruta register usa un método del controlador UserController?
Creo que el nombre no refleja la función del controlador

2021-10-29 21:49 UTC, jortiz3109 commented on routes/web.php
> +    Route::name('register.create')->get('/register', [UserController::class, 'create']);
¿Que ocurre si un usuario con la sesión iniciada accede a esta ruta?
Esta ruta creo que debería ser únicamente para usuarios invitados (guests)

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_registration_screen_can_be_rendered()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_new_users_can_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_required_name_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_required_email_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_uniqued_email_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_valid_name_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_disabled_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_create_date_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_create_id_user_register()
¿Tipo de dato de retorno?

2021-10-29 21:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +<?php
¿Que pasó con los data-providers?
Hay muchos datos repetidos que pueden unificarse

2021-11-02 21:34 UTC, jeantech-zz commented on database/seeders/DatabaseSeeder.php
> +        $this->call(UserSeeder::class);
Si porque en el sistema debe existir un usuario para poder  registrar usuarios

2021-11-02 21:38 UTC, jeantech-zz commented on resources/views/layouts/admin.blade.php
> +                            <li><a href="{{ route('register.create') }}"><em class="pr-2 mdi mdi-account-multiple"></em>@lang('Users')</a></li>
Coloque en enlace para poder que desde el menu se pueda ingresar a registrar a usuarios desde el dashboard, como vi que esta el de permisos.

En donde debería de ir?

2021-11-02 21:44 UTC, jeantech-zz commented on routes/web.php
> +    Route::name('register.create')->get('/register', [UserController::class, 'create']);
Segun el requerimiento para crear usuario debe hacerlo un usuario admin ya que 
"El sistema debe guardar el id del administrador que creó el usuario"

2021-11-25 16:49 UTC, jortiz3109 requested changes
Todavía hay cosillas por mejorar, pero vamos bien

2021-11-25 16:49 UTC, jortiz3109 commented on app/Actions/Register/CreateUserAction.php
> +    public static function execute(array $user): User
¿Este array si debería llamarse user?

2021-11-25 16:49 UTC, jortiz3109 commented on app/Actions/Register/CreateUserAction.php
> +        return auth()->user()->create([
Yo la crearía así:
```php
return User::create([
            'name' =>  $user['name'],
            'email' => $user['email'] ,
            'password' => Hash::make($user['password']),
            'created_by' =>  auth()->id(),
            'updated_by' =>   auth()->id(),
        ]);
```

2021-11-25 16:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        return view('register.create', $viewModel->toArray());
Esta vista debería llamarse users.create

2021-11-25 16:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        $viewModel->collection($users);
No entiendo muy bien como funciona este viewModel

2021-11-25 16:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +    public function store(UserCreateRequest $request)
¿Cual es el tipo de dato que retorna esta función?

2021-11-25 16:49 UTC, jortiz3109 commented on app/Http/Controllers/UserController.php
> +        return redirect()->route('dashboard')->with('success', 'Register created successfully.');
¿Y las traducciones?

2021-11-25 16:49 UTC, jortiz3109 commented on app/Http/Requests/Register/UserCreateRequest.php
> +            'email' => 'required|string|email|max:255|unique:users',
La regla unique te funciona, pero creo que es mas idóneo usarlo así:

```php
Rule::unique('users')->ignore($user->id),
```

2021-11-25 16:49 UTC, jortiz3109 commented on app/ViewModels/Users/CreateViewModel.php
> +    protected function buttons(): array
¿No hay botones para la vista de creación?

2021-11-25 16:49 UTC, jortiz3109 commented on app/ViewModels/Users/CreateViewModel.php
> +    public function filters(): array
Hay que revisar la pertinencia de usar los métodos filters() y data()

2021-11-25 16:49 UTC, jortiz3109 commented on database/migrations/2021_10_24_224610_add_create_update_user.php
> +            $table->foreignId('created_by')->nullable()->constrained('users')->onDelete('cascade');
Ojo con el onDelete de estos constraints, porque pueden derivar en eliminaciones no intencionales de datos.

2021-11-25 16:49 UTC, jortiz3109 commented on database/seeders/UserSeeder.php
> +    public function run()
Valor de retorno?

2021-11-25 16:49 UTC, jortiz3109 commented on database/seeders/UserSeeder.php
> +        $user =User::create([
Este código no cumple con PSR

2021-11-25 16:49 UTC, jortiz3109 commented on database/seeders/UserSeeder.php
> +        event(new Registered($user));
¿Este evento si es necesario?

2021-11-25 16:49 UTC, jortiz3109 commented on resources/views/register/create.blade.php
> +@extends('layouts.admin')
Hay que renombrar esta vista

2021-11-25 16:49 UTC, jortiz3109 commented on resources/views/register/create.blade.php
> +                    @lang('users.buttons.register')
La traducción no debería ser users.buttons.register, sino que podría ser algo como: common.buttons.save

2021-11-25 16:49 UTC, jortiz3109 commented on resources/views/register/create.blade.php
> +                    <b-input type="text" name="name" id="name" value="{{ old('name') }}" maxlength="30"  required></b-input>
Las validaciones permiten hasta 255 caracteres, pero el HTML está limitando a 30

2021-11-25 16:49 UTC, jortiz3109 commented on resources/views/register/create.blade.php
> +                    <b-input type="email" name="email" id="email" value="{{ old('email') }}" maxlength="30" icon="account-lock"  required></b-input>
Las validaciones permiten hasta 255 caracteres, pero el HTML está limitando a 30

2021-11-25 16:49 UTC, jortiz3109 commented on resources/views/register/create.blade.php
> +                    <b-input type="password" name="password" id="password" value="{{ old('password') }}" maxlength="30" icon="lock" required></b-input>
Las validaciones permiten hasta 255 caracteres, pero el HTML está limitando a 30

2021-11-25 16:49 UTC, jortiz3109 commented on resources/views/register/create.blade.php
> +                    <b-input type="password" name="password_confirmation" id="password_confirmation" value="{{ old('password_confirmation') }}" maxlength="30" icon="lock" required></b-input>
Las validaciones permiten hasta 255 caracteres, pero el HTML está limitando a 30

2021-11-25 16:49 UTC, jortiz3109 commented on routes/web.php
> +    Route::name('users.create')->get('/register', [UserController::class, 'create']);
El path de la ruta debería ser: /users/create

2021-11-25 16:49 UTC, jortiz3109 commented on routes/web.php
> +    Route::name('users.store')->post('/register', [UserController::class, 'store']);
El path de la ruta debería ser /users

2021-11-25 16:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +        $response->assertRedirect('dashboard');
¿Esta prueba realmente "prueba" que el usuario fue creado en DB?

2021-11-25 16:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_required_name_user_register(): void
Estas 3 pruebas se pueden unificar en una sola usando un Data Provider
https://github.com/jortiz3109/escuela-php-workshop-1/blob/main/tests/Feature/API/Developers/StoreTest.php

2021-11-25 16:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_create_date_user_register(): void
Yo no agregaría esta prueba, pues es un comportamiento del framework que ya está probado

2021-11-25 16:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function test_create_id_user_register(): void
Creo que este podría ser un enfoque interesante para esta prueba.

```php
$user = User::factory()->create();
$this->actingAs($user)->post('/users', $this->developerData());
$this->assertEquals(User::latest()->first()->created_by, $user->id);
```

2021-11-25 16:49 UTC, jortiz3109 commented on tests/Feature/Register/RegisterUserTest.php
> +    public function developerData(): array
No lo sé Rick... se me hace como falso.

2021-12-28 02:34 UTC, asilvabe requested changes

2021-12-28 02:34 UTC, asilvabe commented on app/Actions/User/UserEnableDisableAction.php
> +class UserEnableDisableAction
Cambiar el nombre por `UserVerificationAction`

2021-12-28 02:34 UTC, asilvabe commented on app/Actions/User/UserStoreAction.php
> +    public static function execute(array $data, User $user): User
Usar esta acción únicamente para crear un nuevo usuario.
Implica que el usuario no debe llegar como un parámetro.
Revisar la lógica de implementación

2021-12-28 02:34 UTC, asilvabe commented on app/Actions/User/UserStoreAction.php
> +        $user->save() ? event(new Registered($user)) : Log::error(trans(''));
¿este evento si debe ir aquí?
Este evento debería generarse sólo cuando el usuario de registra a sí mismo

2021-12-28 02:34 UTC, asilvabe commented on app/Actions/User/UserStoreAction.php
> +    public static function execute(array $data, User $user): User
¿Este método debería ser estático?
¿no es mejor inyectar las dependencias a través del constructor?

2021-12-28 02:34 UTC, asilvabe commented on app/Http/Controllers/UserController.php
> +        UserStoreAction::execute($request->validated(), new User());
Recuerda que el usuario no debe pasarse por aquí, se crea en el action

2021-12-28 02:34 UTC, asilvabe commented on app/Http/Controllers/UserController.php
> +        return view('users.create', $viewModel->toArray());
Quitar el `toArray`

2021-12-28 02:34 UTC, asilvabe commented on app/Http/Requests/Users/UserCreateRequest.php
> +            'password' => ['required', 'confirmed', Rules\Password::defaults()],
Importar la clase Password

2021-12-28 02:34 UTC, asilvabe commented on app/Http/Requests/Users/UserCreateRequest.php
> +            'email' => ['required', 'email', 'max:255',  Rule::unique('users', 'email')->ignore($this->users)],
El `ignore` no debe aplicarse por tratarse de la creación del usuario

2021-12-28 02:34 UTC, asilvabe commented on app/Http/Requests/Users/UserCreateRequest.php
> +            'name' => ['required', 'string', 'max:255', 'regex:/^[a-zA-Z\s]+$/u'],
Revisar si existe una regla para esto y evitar utilizar la expresión regular

2021-12-28 02:34 UTC, asilvabe commented on app/Models/User.php
> +    public function isEmailVerified(self $user): bool
Elminar este parámetro, usarlo son la variable `$this`

2021-12-28 02:34 UTC, asilvabe commented on resources/views/layouts/admin.blade.php
> +                            <li><a href="#"><em class="pr-2 mdi mdi-account-multiple"></em></a></li>
¿en serio debía eliminarse el link de usuarios?

2021-12-28 02:34 UTC, asilvabe commented on resources/views/users/create.blade.php
> +@endsection
Agregar la línea adiciona

2021-12-28 02:34 UTC, asilvabe commented on resources/views/users/create.blade.php
> +                    @lang('users.buttons.save')
Reemplazar todos los usos de @lang por `{{ trans() }}`

2021-12-28 02:34 UTC, asilvabe commented on resources/views/users/create.blade.php
> +                <button type="submit" class="button is-primary is-fullwidth"> <b-icon pack="fas" icon="save"></b-icon>&nbsp;
Agregar desde el viewModel con el array de botones

2021-12-28 02:34 UTC, asilvabe commented on routes/web.php
> +    Route::resource('users', UserController::class);
Agregar `only('create')`

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +    public function authenticated_user_can_view_the_create_view(): void
Reemplazar el comentario por el prefijo `test_`

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(Response::HTTP_OK);
Agregar la asersión que afirma que es una vista (assertViewIs)

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(Response::HTTP_FOUND);
Debe redirigir a la ruta login

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(302);
Usar la constante de la clase Response

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +        $data['updated_by'] = $user->id;
No debe asignarse estos valores aquí, ya que se asignar en la acción

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +        $user = User::factory()->create();
Reemplazar por uso del Trait en toda la clase

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +            'updated_by' => $user->id,
`updated_by` no debe ir aquí

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(302)
Usar la constante de `Response`

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +    public function a_user_store_required_data(array $data, string $field): void
Buscar un mejor nombre: Ej. `test_can_not_create_an_user_with_invaid_data`

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +     * @dataProvider validUserStatusData
¿si es necesario este provider?

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +    public function disabled_user_register(array $data, array $status): void
Pensar en un nombre más descriptivo

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +     * @dataProvider validUserData
No es necesario este provider

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertRedirect('/dashboard');
¿Si debería redirigir a esta ruta?

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +    public function create_id_user_register(array $data): void
Pensar en un nombre mejor

2021-12-28 02:34 UTC, asilvabe commented on tests/Feature/Users/CreateUserTest.php
> +    public function unique_email_user_register(array $data): void
Refactorizar implementando esto en la prueba de validaciones
Recordar la discusión entre Lauana y Alexandre sobre los provider's
Si lo dejas ocmo un test separado eliminar el uso del provider

2021-12-28 02:34 UTC, asilvabe commented on tests/Support/User/UserFeatureDataProvider.php
> +            ],
Incluir las reglas de validación que faltan

2021-12-28 02:34 UTC, asilvabe commented on tests/Support/User/UserFeatureDataProvider.php
> +    public function invalidUserData(): array
Revisar [este código](https://github.com/jortiz3109/simple-scrum-manager/blob/main/tests/DataProviders/Developer/StoreOrUpdaterDataProvider.php) para inspiración

2021-12-28 02:34 UTC, asilvabe commented on tests/Support/User/UserUnitDataProvider.php
> +<?php
Eliminar este archivo

2021-12-28 02:34 UTC, asilvabe commented on tests/Unit/Models/UserTest.php
> +<?php
Eliminar este archivo

2021-12-28 20:41 UTC, juancolo commented on app/Actions/User/UserEnableDisableAction.php
> +class UserEnableDisableAction
corregido

2021-12-28 20:41 UTC, juancolo commented on app/Actions/User/UserStoreAction.php
> +    public static function execute(array $data, User $user): User
corregido

2021-12-28 20:41 UTC, juancolo commented on app/Actions/User/UserStoreAction.php
> +        $user->save() ? event(new Registered($user)) : Log::error(trans(''));
corregido

2021-12-28 20:41 UTC, juancolo commented on app/Http/Controllers/UserController.php
> +        return view('users.create', $viewModel->toArray());
corregido

2021-12-28 20:41 UTC, juancolo commented on app/Http/Controllers/UserController.php
> +        UserStoreAction::execute($request->validated(), new User());
corregido

2021-12-28 20:42 UTC, juancolo commented on app/Http/Requests/Users/UserCreateRequest.php
> +            'email' => ['required', 'email', 'max:255',  Rule::unique('users', 'email')->ignore($this->users)],
corregido

2021-12-28 20:42 UTC, juancolo commented on app/Http/Requests/Users/UserCreateRequest.php
> +            'password' => ['required', 'confirmed', Rules\Password::defaults()],
corregido

2021-12-28 20:42 UTC, juancolo commented on app/Models/User.php
> +    public function isEmailVerified(self $user): bool
corregido

2021-12-28 20:46 UTC, juancolo commented on database/seeders/UserSeeder.php
> +        event(new Registered($user));
corregido

2021-12-28 20:46 UTC, juancolo commented on resources/views/layouts/admin.blade.php
> +                            <li><a href="#"><em class="pr-2 mdi mdi-account-multiple"></em></a></li>
corregido

2021-12-28 20:51 UTC, juancolo commented on resources/views/users/create.blade.php
> +                    @lang('users.buttons.save')
corregido

2021-12-28 20:51 UTC, juancolo commented on routes/web.php
> +    Route::resource('users', UserController::class);
corregido

2021-12-28 21:11 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +    public function authenticated_user_can_view_the_create_view(): void
corregido

2021-12-28 23:23 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +        $user = User::factory()->create();
corregido

2021-12-28 23:23 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(Response::HTTP_OK);
corregido

2021-12-29 00:02 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(Response::HTTP_FOUND);
corregido

2021-12-29 00:02 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +        $data['updated_by'] = $user->id;
corregido

2021-12-29 00:02 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(302);
corregido

2021-12-29 00:02 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +            'updated_by' => $user->id,
corregido

2021-12-29 00:06 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +    public function a_user_store_required_data(array $data, string $field): void
corregido

2021-12-29 00:06 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +            ->assertStatus(302)
corregido

2021-12-29 00:09 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +    public function disabled_user_register(array $data, array $status): void
corregido

2021-12-29 00:09 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +    public function create_id_user_register(array $data): void
corregido

2021-12-29 18:02 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +     * @dataProvider validUserData
corregido

2021-12-29 18:03 UTC, juancolo commented on tests/Support/User/UserFeatureDataProvider.php
> +    public function invalidUserData(): array
corregido

2021-12-29 18:03 UTC, juancolo commented on tests/Support/User/UserFeatureDataProvider.php
> +            ],
corregido

2022-01-03 00:00 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +     * @dataProvider validUserStatusData
Corregido

2022-01-03 00:01 UTC, juancolo commented on tests/Feature/Users/CreateUserTest.php
> +    public function unique_email_user_register(array $data): void
corregido

2022-01-03 00:01 UTC, juancolo commented on tests/Support/User/UserUnitDataProvider.php
> +<?php
corregido

2022-01-03 00:01 UTC, juancolo commented on tests/Unit/Models/UserTest.php
> +<?php
corregido

2022-01-03 03:41 UTC, juancolo commented on app/Http/Requests/Users/UserCreateRequest.php
> +            'name' => ['required', 'string', 'max:255', 'regex:/^[a-zA-Z\s]+$/u'],
No hay una regla para letras y espacios

2022-01-05 03:31 UTC, juancolo commented on resources/views/users/create.blade.php
> +                <button type="submit" class="button is-primary is-fullwidth"> <b-icon pack="fas" icon="save"></b-icon>&nbsp;
realizado

2022-01-17 21:42 UTC, merged