Feature/ep 27 filters tests
jortiz3109/escuela-php-panel pull request #21
Opened 2021-12-13 11:25 UTC by asilvabe

2021-12-21 12:28 UTC, jortiz3109 requested changes

2021-12-21 12:28 UTC, jortiz3109 commented on tests/Feature/Merchants/IndexTest.php
>          $this->assertEquals(1, $merchants->count());
Creo que existe una asersión que permite contar elementos.

2021-12-21 12:28 UTC, jortiz3109 commented on tests/Feature/Merchants/IndexTest.php
> +        $this->assertEquals($showedValue, $merchants->first()->attributesToArray()[$attribute]);
No se entiende muy bien que es lo que se pretende probar

2021-12-21 12:28 UTC, jortiz3109 commented on tests/Feature/Merchants/IndexTest.php
> +                'attribute' => 'multiple',
Creo que podríamos cambiar "multiple" por "query"

2021-12-21 12:28 UTC, jortiz3109 commented on tests/TestCase.php
> +    protected function defaultUser(): Model
En teoría debería devolver un User, no un Model

2021-12-21 12:28 UTC, jortiz3109 commented on tests/TestCase.php
> +    protected function getReflectionProtectedPropertyValue(string $className, string $property): mixed
¿Este método si debería ir en esta clase?

2021-12-21 12:28 UTC, jortiz3109 commented on tests/TestCase.php
> +    protected function defaultUser(): Model
Este método podría ir en un rasgo (**### HasAuthenticatedUser**)

2021-12-21 12:28 UTC, jortiz3109 commented on tests/TestCase.php
> +    protected function getReflectionProtectedPropertyValue(string $className, string $property): mixed
Creo que podría ir en un rasgo.

2021-12-21 12:28 UTC, jortiz3109 commented on tests/Unit/Filters/ModelFilters/MerchantFiltersTest.php
> +<?php
¿Estas pruebas realmente aportan valor?

2021-12-21 12:28 UTC, jortiz3109 commented on tests/Unit/Filters/ModelFilters/PermissionFiltersTest.php
> +<?php
¿Esta clase de pruebas realmente aportan valor?

2021-12-22 23:53 UTC, asilvabe commented on tests/Feature/Merchants/IndexTest.php
>          $this->assertEquals(1, $merchants->count());
Se cambió a asersión

2021-12-22 23:54 UTC, asilvabe commented on tests/Feature/Merchants/IndexTest.php
> +        $this->assertEquals($showedValue, $merchants->first()->attributesToArray()[$attribute]);
Se cambió por un assertSee

2021-12-22 23:54 UTC, asilvabe commented on tests/Feature/Merchants/IndexTest.php
> +                'attribute' => 'multiple',
Se cambió a merchantQuery

2021-12-22 23:54 UTC, asilvabe commented on tests/TestCase.php
> +    protected function defaultUser(): Model
Se movieron los métodos a un trait

2021-12-28 14:49 UTC, asilvabe commented on tests/Unit/Filters/ModelFilters/MerchantFiltersTest.php
> +<?php
Se eliminaron y se creó `Tests\Unit\Filters\ConditionsTest.php`

2021-12-28 14:50 UTC, asilvabe commented on tests/Unit/Filters/ModelFilters/PermissionFiltersTest.php
> +<?php
Se eliminaron y se creó `Tests\Unit\Filters\ConditionsTest.php`

2022-01-03 23:55 UTC, merged