Feature/ep 28 transaction index
jortiz3109/escuela-php-panel pull request #22
Opened 2021-12-13 22:59 UTC by lauana-oh

2021-12-21 13:40 UTC, jortiz3109 requested changes

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/Conditions/Merchants/Country.php
> +namespace App\Filters\Conditions\Merchants;
¿Este filtro aplica únicamente a Merchants o podría aplicar a múltiples entidades?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/Conditions/Merchants/Currency.php
> +namespace App\Filters\Conditions\Merchants;
¿Este filtro aplica únicamente a Merchants o también podría aplicar a otras entidades?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/Conditions/Transactions/Date.php
> +        if ($dates = $criteria->value()) {
¿La condición realmente debe validar que el criterio tenga un valor?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/Conditions/Transactions/Date.php
> +                Carbon::parse($dates[1])->toDateString() . ' 23:59:59',
No lo sé rick... creo que podríamos aplicar un formato a la fecha usando carbon.
`
>>> now()->startOfDay()->toDateTimeString()
=> "2021-12-21 00:00:00"
>>> now()->endOfDay()->toDateTimeString()
=> "2021-12-21 23:59:59"
`

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/Conditions/Transactions/Merchant.php
> +class Merchant extends Condition
¿Esta condición no debería llamarse MerchantName?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/Conditions/Transactions/PaymentMethod.php
> +class PaymentMethod extends Condition
¿Esta clase no podría llamarse PaymentMethodName?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Filters/ModelFilters/MerchantFilters.php
>          'currency' => Currency::class,
Recuerda cambiar los nombres de las condiciones para que sea mas fácil de entender

2021-12-21 13:40 UTC, jortiz3109 commented on app/Helpers/AmountHelper.php
> +        return $symbol . app(IntlMoneyFormatter::class)->format($money);
No se... no me convence la forma como se agrega el símbolo al formato.

Yo consultaría como debería formatearse de acuerdo a las normas de formato para cada lenguaje

2021-12-21 13:40 UTC, jortiz3109 commented on app/Helpers/AmountHelper.php
> +    public static function format(int $amount, string $currency)
¿Donde quedó el tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Controllers/LoginLogController.php
> +    public function __invoke(LoginLogsIndexViewModel $viewModel)
¿Y el tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Controllers/TransactionController.php
> +        $transactions = Transaction::filter($request->safe()->collect()->get('filters', []))->paginate();
¿Y no es mas fácil usar esto?
`$request->validated()`

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Requests/Transactions/IndexRequest.php
> +            'filters'          => ['filled', 'array'],
¿Estos espacios demás que?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Requests/Transactions/IndexRequest.php
> +        return [
yo agregaría 'bail' como parámetro para no desgastar las validaciones si una condición falla

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Requests/Transactions/IndexRequest.php
> +            'filters.date.*' => ['date'],
Yo cambiaría 'date' por 'date_format'

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Requests/Transactions/IndexRequest.php
> +    protected function prepareForValidation()
¿El tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Requests/Transactions/IndexRequest.php
> +                    'date' => explode(' - ', $date),
Yo echaría una segunda mirada a este método, porque se me hace que no debería ir acá

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Resources/Transactions/IndexResource.php
> +            'date' => $this->executed_at->toDateString(),
Yo creo que podríamos implementar un helper que nos ayude a formatear fechas de la manera correcta

2021-12-21 13:40 UTC, jortiz3109 commented on app/Http/Resources/Transactions/IndexResource.php
> +        return [
Validemos si el modelo me permite de alguna manera hacer este método mas pequeño.

2021-12-21 13:40 UTC, jortiz3109 commented on app/View/Composers/PaymentMethodsComposer.php
> +            DB::table('payment_methods')->select('name')->orderBy('name')->get(),
¿No es mas idóneo usar el id como dato para buscar en DB?

2021-12-21 13:40 UTC, jortiz3109 commented on app/ViewComponents/Display/DisplayComponent.php
> +    public function __construct(string $label, ?string $class = '')
Yo haría un doble check con el tema de las clases CSS en componentes PHP

2021-12-21 13:40 UTC, jortiz3109 commented on app/ViewComponents/Display/DisplayComponent.php
> +    abstract public function renderField(array $value, string $key): View;
¿Si recibe un arreglo, el nombre de la variable es $value o $values?

2021-12-21 13:40 UTC, jortiz3109 commented on app/ViewComponents/Display/DisplayLinkComponent.php
> +            'value' => $value[$key],
Este machete me cortó 2 dedos

2021-12-21 13:40 UTC, jortiz3109 commented on app/ViewModels/Transactions/TransactionIndexViewModel.php
> +            'date' => new DisplayTextComponent('transactions.fields.date', 'has-text-centered'),
¿No hay manera de "desligar" el CSS de PHP?

2021-12-21 13:40 UTC, jortiz3109 commented on database/factories/MerchantFactory.php
> +            'country_id'  => Country::all()->random()->id,
Eloquent tiene un método inRandomOrder()->first()

2021-12-21 13:40 UTC, jortiz3109 commented on database/factories/TransactionFactory.php
> +            'currency_id' => Currency::all()->random()->id,
usar inRandomOrder de Eloquent

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/display/label.blade.php
> +<th scope="col" class="{{ $class }}">
la vista se llama label, pero renderiza un th

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/display/link.blade.php
> +<td class="{{ $class }}">
Creo que sería conveniente reorganizar esta vista parcial en una estructura un poco mas ordenada

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/display/text.blade.php
> +<td class="{{ $class }}">
Este component renderiza un texto, pero dentro de una tabla

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/country.blade.php
>          placeholder="@lang('merchants.placeholders.select_country')" expanded
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/country.blade.php
>          placeholder="@lang('merchants.placeholders.select_country')" expanded
Se debería usar {{ trans() }}

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/currency.blade.php
>          placeholder="@lang('merchants.placeholders.select_currency')" expanded
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/date.blade.php
> +    label="@lang('Date')"
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/merchant.blade.php
> +    label="@lang('Merchant')"
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/payment_method.blade.php
> +    label="@lang('transactions.fields.payment_method')"
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/reference.blade.php
> +    label="@lang('Reference')"
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/partials/filters/status.blade.php
> +    label="@lang('transactions.fields.status')"
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on resources/views/transactions/show.blade.php
>      <b-field horizontal label="@lang('Total amount')">
Laravel no recomienda usar @lang pues tiene implicaciones en seguridad

2021-12-21 13:40 UTC, jortiz3109 commented on tests/Feature/Transactions/IndexTest.php
> +    public function test_it_can_filter_transactions_by_status()
El tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on tests/Feature/Transactions/IndexTest.php
> +    public function test_it_can_filter_transactions_by_merchant()
El tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on tests/Feature/Transactions/IndexTest.php
> +    public function test_it_can_filter_transactions_by_reference()
El tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on tests/Feature/Transactions/IndexTest.php
> +    public function test_it_can_filter_transactions_by_payment_method()
El tipo de dato de retorno?

2021-12-21 13:40 UTC, jortiz3109 commented on tests/Feature/Transactions/IndexTest.php
> +    public function test_it_can_filter_transactions_by_date()
El tipo de dato de retorno?

2021-12-24 05:04 UTC, juancolo commented on app/Http/Resources/Transactions/IndexResource.php
> +class IndexResource extends JsonResource
@lauana-oh por convención no deberíamos nombrar esta clase como MerchantIndexResource?

2021-12-27 21:25 UTC, merged