Feature/EP-8-enable-user-button
jortiz3109/escuela-php-panel pull request #25
Opened 2021-12-22 20:28 UTC by JuanZea

2021-12-22 23:11 UTC, asilvabe commented on app/Filters/Filter.php
> +            (is_null($value)) ?: $conditionClass::append($this->query, new Criteria($value));
Aprovechemos que se hizo esta mejora y eliminemos el `null` en los tipos de retorno en `app\Filters\Criteria.php`

2021-12-22 23:11 UTC, asilvabe commented on app/Http/Controllers/Api/UserController.php
> +class UserController extends Controller
¿qué opinas de usar un controlador dedicado para esta acción? podría llamarse `ToggleUserStatusController`
https://github.com/adamwathan/laracon2017/pull/2

2021-12-23 02:08 UTC, JuanZea commented on app/Http/Controllers/Api/UserController.php
> +class UserController extends Controller
Una idea excelente!, lo deje como UserStatusController > toggle()

2021-12-23 16:35 UTC, jortiz3109 requested changes

2021-12-23 16:35 UTC, jortiz3109 commented on app/Filters/Conditions/Status.php
> +        $query->when($criteria == 'enabled', function ($q) {
¿No hay una forma mas "elegante" de hacer este criterio

2021-12-23 16:35 UTC, jortiz3109 commented on app/Filters/Filter.php
> +            (is_null($value)) ?: $conditionClass::append($this->query, new Criteria($value));
¿Esto es para?

2021-12-23 16:35 UTC, jortiz3109 commented on app/Filters/ModelFilters/UserFilters.php
> +    protected array $applicableConditions = [
¿Acá no cabría una implementación del patrón cadena de responsabilidad?

2021-12-23 16:35 UTC, jortiz3109 commented on app/Http/Controllers/Api/UserController.php
> +    public function toggleUserStatus(User $user): User
No lo sé rick... no me convence esta implementación

2021-12-23 16:35 UTC, jortiz3109 commented on app/Http/Requests/Users/IndexRequest.php
> +            'filters' => ['filled', 'array'],
¿No sería chevere agregar una regla **in** para limitar el tipo de filtros que se pueden enviar en la petición?

2021-12-23 16:35 UTC, jortiz3109 commented on app/Models/User.php
> +        'date_formatted',
¿Que es este campo?

2021-12-23 16:35 UTC, jortiz3109 commented on app/Models/User.php
> +    public function getDateFormattedAttribute(): string
Nonononononono.... el modelo no debería saber como formatear una fecha

2021-12-23 16:35 UTC, jortiz3109 commented on app/Models/User.php
> +    public function getStatusAttribute(): string
¿El status si debería entregarse así?

2021-12-23 16:35 UTC, jortiz3109 commented on public/js/app.js
>  (self["webpackChunk"] = self["webpackChunk"] || []).push([["/js/app"],{
¿Este asset no debería estar compilado para producción?

2021-12-23 16:35 UTC, jortiz3109 commented on public/js/manifest.js
>  /******/ 		};
¿Esto no debería estar compilado para producción?

2021-12-23 16:35 UTC, jortiz3109 commented on resources/views/filters.blade.php
> +            @php
¿Esto si debería ir en la vista?

2021-12-28 00:19 UTC, asilvabe requested changes

2021-12-28 00:19 UTC, asilvabe commented on app/Http/Controllers/Api/UserStatusController.php
> +
Refactorizar a uso de interfaz. Ej. `Togglable`

2021-12-28 00:19 UTC, asilvabe commented on resources/js/components/buttons/StatusButton.vue
> +    <button class="button" @click="switchUserStatus" :class="status === 'Enabled' ? 'is-success' : 'is-danger'">
Este estado debe manejarse como un booleano

2021-12-28 00:19 UTC, asilvabe commented on resources/js/components/buttons/StatusButton.vue
> +        <span class="text-red-500">{{ status }}</span>
Este texto podría reemplazarse por un slot

2021-12-28 00:19 UTC, asilvabe commented on resources/views/users/index.blade.php
> +                    <status-button url="{{ config('app.url') }}" user-id="{{ $user->id }}" user-status="{{ $user->status }}" email-verified="{{ false }}"></status-button>
Quitarle la responsabilidad de traducción al modelo User

2021-12-28 00:19 UTC, asilvabe commented on resources/views/users/index.blade.php
>                  <td>{{ $user->date_formatted }}</td>
Refactorizar: quitarle la responsabilidad de dar formato al modelo.

2021-12-28 00:19 UTC, asilvabe commented on tests/Feature/Users/StatusTest.php
> +}
Dividir en las pruebas que sean necesarias. Implemantar AAA

2022-01-13 13:39 UTC, jortiz3109 commented on tests/Feature/Users/StatusTest.php
> +}
Recuerda que el patrón AAA se aplica cuando sea posible hacerlo.

2022-01-13 15:39 UTC, asilvabe commented
@JuanZea por favor actualiza esta rama con los cambios que se fusionaron de la tarea de habilitación de medios de pago, y sube los archivos front compilados para producción

2022-01-13 17:02 UTC, merged