Feature/ep 41 update permissions
jortiz3109/escuela-php-panel pull request #27
Opened 2021-12-29 15:08 UTC by lauana-oh

2021-12-29 15:55 UTC, asilvabe requested changes
¿cómo hace el usuario para llegar al formulario de edición de un permiso?
No vi el enlace desde el listado de permisos

2021-12-29 15:55 UTC, asilvabe commented on app/Actions/Permissions/PermissionUpdateAction.php
> +    public function execute(Model $permission, Request $request): Model
Creo que es mejor que los datos no se pasen como un objeto de Request, así este método puede usarse en otro contexto distinto a la de una solicitud HTTP.
¿qué tal un array? ¿o un DTO 😁?

2021-12-29 15:55 UTC, asilvabe commented on resources/lang/en/permissions.php
> +        'description' => 'Enter permission description...',
¿por qué los puntos suspensivos?

2021-12-29 15:55 UTC, asilvabe commented on tests/Feature/Permissions/EditTest.php
> +        $response = $this->actingAs($this->defaultUser())->get(route(self::PERMISSIONS_ROUTE_NAME, $this->permission->id));
¿qué opinas de dividir en múltiples líneas?

2021-12-29 15:55 UTC, asilvabe commented on tests/Feature/Permissions/EditTest.php
> +        $response = $this->actingAs($this->defaultUser())->get(route(self::PERMISSIONS_ROUTE_NAME, $this->permission->id));
lo mismo que el anterior

2021-12-29 16:26 UTC, lauana-oh commented on resources/lang/en/permissions.php
> +        'description' => 'Enter permission description...',
Yo use el mismo formato que Juan ricardo uso en los merchants. Creo que deberiamos decidir si dejamos en los dos o quitamos de los dos

2021-12-29 16:28 UTC, lauana-oh commented on tests/Feature/Permissions/EditTest.php
> +        $response = $this->actingAs($this->defaultUser())->get(route(self::PERMISSIONS_ROUTE_NAME, $this->permission->id));
listo

2021-12-29 16:28 UTC, lauana-oh commented on tests/Feature/Permissions/EditTest.php
> +        $response = $this->actingAs($this->defaultUser())->get(route(self::PERMISSIONS_ROUTE_NAME, $this->permission->id));
listo

2021-12-29 16:31 UTC, lauana-oh commented on app/Actions/Permissions/PermissionUpdateAction.php
> +    public function execute(Model $permission, Request $request): Model
Yo creo que arreglos son formatos mas dificiles de estandarizar, exigen validaciones, etc.
Aun creo que recibir el request es una buena opcion en ese caso.

2021-12-29 16:33 UTC, lauana-oh commented on app/Actions/Permissions/PermissionUpdateAction.php
> +    public function execute(Model $permission, Request $request): Model
Separar eso en otra clase creo que tal vez seria el antipatron de atomitizar demasiado las clases. Esa clase ya tiene una sola razon de existir: guardar los datos del request en el modelo. Que piensas?

2021-12-29 16:43 UTC, asilvabe commented on app/Actions/Permissions/PermissionUpdateAction.php
> +    public function execute(Model $permission, Request $request): Model
mmmm seeeee, podemos dejarla así. Pero si más adelante hay que soportar que guarde desde otro origen distinto a un request esa tarea te toca a ti 😂

2021-12-29 16:45 UTC, asilvabe commented on resources/lang/en/permissions.php
> +        'description' => 'Enter permission description...',
ah bueno, era curiosidad

2022-01-04 05:28 UTC, asilvabe reviewed
Se revisaron las modificaciones recientes

2022-01-13 04:22 UTC, asilvabe commented
@lauana-oh creo que resolviendo los conflictos este PR ya puede fusinarse, y con ello el #33

2022-01-13 13:08 UTC, merged