Feature/ep 34 transaction geolocation
jortiz3109/escuela-php-panel pull request #28
Opened 2022-01-02 18:29 UTC by DevAlexandreCR

2022-01-03 00:08 UTC, lauana-oh requested changes

2022-01-03 00:08 UTC, lauana-oh commented on resources/js/app.js
> +import MapView from './components/MapView'
Sería bueno llamar el componente de IMapView para seguir el patrón de los demás

2022-01-03 00:08 UTC, lauana-oh commented on resources/js/app.js
> +Vue.component('map-view', MapView);
Sería bueno que se llamara i-map-view

2022-01-03 00:08 UTC, lauana-oh commented on resources/sass/map.scss
> +#map {
Si eso solo es usado en un componente específico, de pronto no sería mejor tener como style scoped directamente en el componente?

2022-01-03 00:08 UTC, lauana-oh commented on .env.example
> +MIX_MAP_API_KEY=
Creo que sería mejor tener variables separadas para cada tipo de servicio. Pq así cuando se cambia de servicio, solo hay que cambiar una variable.

2022-01-03 00:08 UTC, lauana-oh commented on app/ViewComponents/Display/DisplayMapComponent.php
> +        return view('partials.display.table.th', [
Que piensas si creamos una vista específica "en vacio" en vez de enviar el label `''`?

2022-01-03 00:08 UTC, lauana-oh commented on resources/js/maps/map.js
> +        if (typeof this.service.render === 'function') {
De pronto podríamos invertir la comparación para evitar el else:
```
if (typeof this.service.render !== 'function') {
            throw new Error('Service has not render function')
 }

 this.service.render(LatLng)
```

2022-01-03 00:08 UTC, lauana-oh commented on resources/views/transactions/show.blade.php
> -    <h3 class="title is-5">@lang('Transaction data')</h3>
No sería más interesante borrar esa vista y usar la vista `modules.show`?

2022-01-03 00:08 UTC, lauana-oh commented on testsjs/unit/components/MapView.spec.js
> +
Si hay 2 servicios de mapa, sería bueno probar las dos implementaciones

2022-01-03 00:08 UTC, lauana-oh commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'total_amount' => $this->resource->currency->alphabetic_code . AmountHelper::format(
Que ganamos en tener el código de la moneda aquí cuando hay un campo separado para eso?

2022-01-03 23:20 UTC, DevAlexandreCR commented on resources/js/app.js
> +Vue.component('map-view', MapView);
Lo que pasa es que los otros son inputs por eso llevan el "I" prefijo

2022-01-03 23:26 UTC, DevAlexandreCR commented on resources/sass/map.scss
> +#map {
se usa tambien el la vista map.blade.php

2022-01-03 23:32 UTC, DevAlexandreCR commented on .env.example
> +MIX_MAP_API_KEY=
MIX_MAP_SERVICE="LEAFLET" es para seleccionar el servicio
MIX_MAP_API_KEY= es para la api_key de google, leaflet no requiere

2022-01-03 23:35 UTC, DevAlexandreCR commented on app/ViewComponents/Display/DisplayMapComponent.php
> +        return view('partials.display.table.th', [
hecho

2022-01-03 23:41 UTC, DevAlexandreCR commented on resources/js/maps/map.js
> +        if (typeof this.service.render === 'function') {
hecho

2022-01-03 23:48 UTC, DevAlexandreCR commented on resources/views/transactions/show.blade.php
> -    <h3 class="title is-5">@lang('Transaction data')</h3>
- una sería refactorizar las otras implementaciones de los showviewmodels para que el array de fields tenga el mismo formato
- la otra sería agregar un @if ( is_array() )  en la vista modules.show .
Yo definí hacerla aparte pues para no usar validaciones que mas adelante se vuelvan más complejas. Ya tu me dirás si la cambio

2022-01-04 00:34 UTC, DevAlexandreCR commented on testsjs/unit/components/MapView.spec.js
> +
hecho

2022-01-04 00:38 UTC, DevAlexandreCR commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'total_amount' => $this->resource->currency->alphabetic_code . AmountHelper::format(
corregido

2022-01-04 00:57 UTC, DevAlexandreCR commented on resources/js/app.js
> +Vue.component('map-view', MapView);
hecho agregado P prefijo

2022-01-04 00:57 UTC, DevAlexandreCR commented on .env.example
> +MIX_MAP_API_KEY=
hecho: cambiado nombre de la variable

2022-01-04 14:46 UTC, jortiz3109 requested changes

2022-01-04 14:46 UTC, jortiz3109 commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'payer_name' => $this->resource->payer->name,
¿Estos campos no deberían ser arrays?

2022-01-04 14:46 UTC, jortiz3109 commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'ip_address' => $this->resource->ip_address,
¿No puede usarse este campo para renderizar el componente de geolocalización?

2022-01-04 14:46 UTC, jortiz3109 commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'currency' => $this->resource->currency->name . ' (' . $this->resource->currency->alphabetic_code . ')',
Esto se me hace un poco raro

2022-01-04 14:46 UTC, jortiz3109 commented on app/ViewComponents/Display/DisplayImageComponent.php
> +    public function renderField(array $model, string $key): View
¿Este campo si debería llamarse model?

2022-01-04 14:46 UTC, jortiz3109 commented on app/ViewModels/Transactions/TransactionDetailsViewModel.php
> +            trans('transactions.titles.data') => [
Me parece un poco peligroso esto

2022-01-04 14:46 UTC, jortiz3109 commented on resources/js/components/PMapView.vue
> +            <img id="map-error" :src="'/img/mapError.png'" alt="Map Error">
¿Este texto alternativo no podría ser mas descriptivo?

2022-01-04 14:46 UTC, jortiz3109 commented on resources/js/components/PMapView.vue
> +            default: null,
¿Si es requerido si necesito un valor por defecto?

2022-01-04 14:46 UTC, jortiz3109 commented on resources/js/maps/services/GeoIP.js
> +        return axios.get(this.route + ip + '?access_key=' + this.apiKey)
¿No podría implementarse este servicio en PHP de tal forma que me permita tener los campos en la DB? y así ahorrarme este llamado cada vez que cargo la página?

2022-01-04 14:46 UTC, jortiz3109 commented on resources/js/maps/services/googleMaps.js
> +                zoom: 8,
¿Que pasa si quisiera cambiar el zoom por defecto?

2022-01-04 14:46 UTC, jortiz3109 commented on resources/views/layouts/app.blade.php
>      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@6.3.95/css/materialdesignicons.min.css">
¿Estamos usando FontAwesome o Material design icons

2022-01-04 14:46 UTC, jortiz3109 commented on resources/views/layouts/app.blade.php
> +    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
Deberíamos buscar la manera de importarlos únicamente cuando se visualice el mapa

2022-01-04 14:46 UTC, jortiz3109 commented on tests/unit/example.spec.js
> +import { shallowMount } from '@vue/test-utils'
¿Este test de prueba si debería venir?

2022-01-10 21:19 UTC, DevAlexandreCR commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'payer_name' => $this->resource->payer->name,
para mantener la estructura en los viewmodels deben mantener esa estructura

2022-01-10 21:21 UTC, DevAlexandreCR commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'ip_address' => $this->resource->ip_address,
debe tener una key diferente para el mapa ya que el viewmodel con la key define cual componente renderizar

2022-01-10 21:38 UTC, DevAlexandreCR commented on app/Http/Resources/Transactions/TransactionShowResource.php
> +            'currency' => $this->resource->currency->name . ' (' . $this->resource->currency->alphabetic_code . ')',
cambiado a un componente aparte

2022-01-10 21:43 UTC, DevAlexandreCR commented on app/ViewModels/Transactions/TransactionDetailsViewModel.php
> +            trans('transactions.titles.data') => [
ahora se llama al metodo tran desde la vista

2022-01-10 21:45 UTC, DevAlexandreCR commented on resources/views/layouts/app.blade.php
>      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@6.3.95/css/materialdesignicons.min.css">
fuera del scope de este PR

2022-01-10 21:56 UTC, DevAlexandreCR commented on resources/views/layouts/app.blade.php
> +    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
ahra se importa solo desde la vista show de transactions

2022-01-10 21:57 UTC, DevAlexandreCR commented on tests/unit/example.spec.js
> +import { shallowMount } from '@vue/test-utils'
removido

2022-01-10 22:03 UTC, DevAlexandreCR commented on resources/js/maps/services/googleMaps.js
> +                zoom: 8,
se agregó variable d entorno para ese valor por defecto

2022-01-11 00:35 UTC, DevAlexandreCR commented on resources/js/maps/services/GeoIP.js
> +        return axios.get(this.route + ip + '?access_key=' + this.apiKey)
ahora el servicio se consume desde php y se guarda en base de datos, solo se consume este servicio cuando se consulta la transaccion, para no guardar ese dato para todas las transacciones

2022-01-11 12:26 UTC, merged