Feature/ep 47 currencies index
jortiz3109/escuela-php-panel pull request #29
Opened 2022-01-04 04:35 UTC by asilvabe

2022-01-04 15:19 UTC, jortiz3109 requested changes

2022-01-04 15:19 UTC, jortiz3109 commented on app/Filters/ModelFilters/CurrencyFilters.php
> +        $this->query->select(['name', 'alphabetic_code', 'symbol']);
¿Y no requieres el ID de la moneda para nada?

2022-01-04 15:19 UTC, jortiz3109 commented on app/ViewModels/Currencies/CurrencyIndexViewModel.php
> +        return [];
Creo que acá podemos aplicar el principio de segregación de interfaces SOLID para no obligar a esta implementación a desarrollar métodos que no necesita

2022-01-04 15:19 UTC, jortiz3109 commented on database/migrations/2021_11_05_022348_create_currencies_table.php
> +            $table->unsignedTinyInteger('minor_unit')->nullable();
¿La unidad menor si puede ser nulo?

2022-01-04 15:19 UTC, jortiz3109 commented on database/migrations/2021_11_05_022348_create_currencies_table.php
> +            $table->string('alphabetic_code', 3);
¿Este código alfabético debería ser un string o puede ser un char?

2022-01-04 15:19 UTC, jortiz3109 commented on database/migrations/2021_11_05_022348_create_currencies_table.php
> +            $table->string('symbol', 10);
¿Un simbolo de 10 caracteres?

2022-01-04 15:19 UTC, jortiz3109 commented on database/seeders/CurrencySeeder.php
>      public function run()
¿Donde está el tipo de dato de retorno?

2022-01-04 15:19 UTC, jortiz3109 commented on database/seeders/CurrencySeeder.php
> +        $currencies = json_decode(file_get_contents(__DIR__ . '/currencies.json'), true);
Creo que no deberíamos almacenar estos ficheros json en el mismo directorio de los seeders

2022-01-04 15:19 UTC, jortiz3109 commented on database/seeders/CurrencySeeder.php
> +        foreach ($currencies as $currency) {
¿No podemos optimizar los llamados a base de datos enviando chunks de 50 currencies a crear?

2022-01-04 15:19 UTC, jortiz3109 commented on resources/views/currencies/index.blade.php
> +@section('content')
¿Porque no estamos usando la metodología que implementamos para comercios y transacciones?

2022-01-04 15:19 UTC, jortiz3109 commented on resources/views/currencies/index.blade.php
> +            <th scope="col">@lang('currencies.fields.name')</th>
OJO que el uso de la directiva @lang es insegura

2022-01-09 00:15 UTC, asilvabe commented on database/migrations/2021_11_05_022348_create_currencies_table.php
> +            $table->unsignedTinyInteger('minor_unit')->nullable();
Sí. En el archivo que tenemos de monedas hay al menos 170 monedas que no tienen unidad menor.

2022-01-09 00:15 UTC, asilvabe commented on app/Filters/ModelFilters/CurrencyFilters.php
> +        $this->query->select(['name', 'alphabetic_code', 'symbol']);
Para el estado actual del sistema no se está requeriendo el id de la moneda en el índice

2022-01-09 00:20 UTC, asilvabe commented on database/seeders/CurrencySeeder.php
> +        $currencies = json_decode(file_get_contents(__DIR__ . '/currencies.json'), true);
Se movió a resources/data_sources

2022-01-09 00:21 UTC, asilvabe commented on database/seeders/CurrencySeeder.php
>      public function run()
Corregido

2022-01-09 00:23 UTC, asilvabe commented on database/migrations/2021_11_05_022348_create_currencies_table.php
> +            $table->string('alphabetic_code', 3);
Cambiado por un campo tipo char

2022-01-09 00:32 UTC, asilvabe commented on database/migrations/2021_11_05_022348_create_currencies_table.php
> +            $table->string('symbol', 10);
Se cambió por 15. La moneda con código NPR (id 67) tiene un símbolo que ocupa 12 caracteres

2022-01-09 00:51 UTC, asilvabe commented on app/ViewModels/Currencies/CurrencyIndexViewModel.php
> +        return [];
Se refactorizó delegando la implementación del método `buttons()` a la clase `app/ViewModels/IndexViewModel.php`
Con ello, se eliminó la necesidad de implementarlo en los IndexViewModel de accesos, monedas, comercios, permisos y transacciones

2022-01-09 01:05 UTC, asilvabe commented on resources/views/currencies/index.blade.php
> +            <th scope="col">@lang('currencies.fields.name')</th>
Se cambió por el método `trans()`

2022-01-09 01:35 UTC, asilvabe commented on database/seeders/CurrencySeeder.php
> +        foreach ($currencies as $currency) {
Optimizado según lo sugerido

2022-01-09 03:05 UTC, asilvabe commented on resources/views/currencies/index.blade.php
> +@section('content')
Metodología implementada

2022-01-11 12:27 UTC, merged